version: '3.9'

services:
  web:
    image: node:16
    ports:
      - "${LOCAL_WEB_PORT:-8000}:8000"
    volumes:
      - "./:/app"
    working_dir: /app
    command: [bash, -c, "npm install && npm run serve"]
  hardhat-node:
    image: node:16
    ports:
      - "8545:8545"
    volumes:
      - "./hardhat:/app"
    working_dir: /app
    command: [bash, -c, "npm install && npx hardhat --network hardhat node"]
